# .github/workflows/userfetch.yml

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    # every day
    - cron:  '0 0 * * *'

jobs:
  sample_job:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/checkout@v2

      - name: userfetch
        uses: userfetch/userfetch-action@v1
        with:
          # path is relative to project root
          config: '/config.mjs'   # input
          svg: '/card.svg'        # output
        env:
          # the token you created in step 2
          github_token: ${{ secrets.GH_PAT }}

      - name: commit
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am '🤖 Daily update!' | true
          git push
